[project]
name = "flask_tabler_icons"
authors = [{ name = "Lix Xu", email = "xuzenglin@gmail.com" }]
description = "a collection of jinja macros for tabler icons"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE.txt" }
keywords = ["flask_tabler_icons"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dependencies = ["flask", "flask_assets"]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = { attr = "flask_tabler_icons.__version__" }

[project.urls]
"Homepage" = "https://github.com/lixxu/flask-tabler-icons"
"Bug Tracker" = "https://github.com/lixxu/flask-tabler-icons/issues"

[build-system]
requires = ["setuptools>=61.0", "wheel", "cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# include-package-data = true
py-modules = ["_custom_build"]

[tool.setuptools.cmdclass]
build_py = "_custom_build.build_py"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*", "docs*", "examples*"]

[tool.setuptools.package-data]
flask_tabler = ["static/**", "templates/**"]
